// wap in C to implement parity checker based on the parity bit generated by the parity generator

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

char calculate_parity(char *data) {
    char parity = '0';
    for (int i = 0; i < strlen(data) - 1; i++) {
        if (data[i] == '1')
            // XOR operation
            parity = (parity == '0') ? '1' : '0';
    }
    return parity;
}

int main() {
    char *data = NULL, received_bit;
    int n;

    printf("\nEnter the size of data word: ");
    scanf("%d", &n);

    data = (char *)calloc(n + 1, sizeof(char));

    printf("\nEnter the data word [in binary]: ");
    fflush(stdin);

    // Use fgets to avoid buffer overflow
    fgets(data, n + 1, stdin);

    printf("\nEnter the received bit: ");
    fflush(stdin);
    scanf(" %c", &received_bit);

    char parity = calculate_parity(data);

    printf("\nParity bit for the data word: %c\n", parity);

    if (parity == received_bit)
        printf("No error detected\n");
    else
        printf("Error detected\n");

    // Check if parity is odd or even
    int num_set_bits = 0;
    for (int i = 0; i < strlen(data) - 1; i++) {
        if (data[i] == '1') {
            num_set_bits++;
        }
    }

    if (num_set_bits % 2 == 0)
        printf("Parity is even\n");
    else
        printf("Parity is odd\n");

    free(data);

    return 0;
}
