// wap in C to implement parity checker based on the parity bit generated by the parity generator

#include<stdio.h>
#include<stdlib.h>
#include<stdbool.h>
#include<string.h>

bool check_parity(char *data){
    int count=0;
    for(int i=0; i<strlen(data); i++){
        if(data[i] == '1')
            count++;
    }
    if(count%2 == 0)
        return true;
    else
        return false;
}

int main(){
    char *data=NULL; int n, count=0;
    printf("\n\tEnter the number of bits in data word [in binary]: ");
    scanf("%d", &n);

    data = (char *)calloc(n, sizeof(char));

    printf("\n\tEnter the data word: ");
    fflush(stdin);
    gets(data);

    if(check_parity(data))
        printf("\n\tThe data word is correct!");
    else
        printf("\n\tThe data word is incorrect!");

    free(data); data = NULL;
    return 0;
}