// wap in C to implement parity checker based on the parity bit generated by the parity generator

#include<stdio.h>
#include<stdlib.h>
#include<string.h>

char calculate_parity(char *data){
    char parity = '0';
    for(int i=0; i<strlen(data)-1; i++){
        if(data[i] == '1')
            //XOR operation
            parity = (parity == '0') ? '1' : '0';
    }
    return parity;
}

int main(){
    char *data=NULL, received_bit; int n;
    printf("\n\tEnter the size of data word: ");
    scanf("%d", &n);

    data = (char *)calloc(n+1, sizeof(char));

    printf("\n\tEnter the data word [in binary]: ");
    fflush(stdin);
    gets(data);

    printf("\n\tEnter the received bit: ");
    fflush(stdin);
    scanf("%c", &received_bit);

    char parity = calculate_parity(data);
    if(parity == received_bit)
        printf("\n\tNo error detected\n");
    else
        printf("\n\tError detected\n");

    free(data); data = NULL;
    return 0;
}